spring.application.name=Spring-MVC
server.port=8080
server.servlet.context-path=/api

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mvctest
spring.datasource.username=postgres
spring.datasource.password=3008
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql