### Health Check
GET http://localhost:8080/actuator/health

### GET all Users
GET {{localhost}}/api/user

### GET user By id
GET {{localhost}}/api/user/11

### Create User
POST {{localhost}}/api/user
Content-Type: application/json

{
  "name": "",
  "email": "manoj@test.com",
  "password": "pass123"
}

### Update User
PUT {{localhost}}/api/user/11
Content-Type: application/json

{
  "name": "Manoj S",
  "email": "manoj123@test.com",
  "password": "pass@#123"
}

### Delete User
DELETE {{localhost}}/api/user/11

### Patch User
PATCH {{localhost}}/api/user/1
Content-Type: application/json

{
  "email": "manu"
}